/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internship;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author mrx
 */
public class Internship extends JFrame {

    // <editor-fold defaultstate="collapsed" desc="All variables">
    static final String LOGIN = "login";
    static final String STUDENTREG = "studentreg";
    static final String MANAGER = "manager";
    
    static Internship internship;
    static Login login;
    static StudentReg studentReg;
    
    static Container pane;
    static CardLayout cl;
    
    static Connection conn;
    static Statement st, st2;
    static PreparedStatement ps;
    static ResultSet rs, rs2;
    // </editor-fold>
    
    /**
     * Creates new form Internship2
     */
    public Internship() {
        super("Internship");
        initComponents();
    }
    
    static void setsize(int width, int height) {
        internship.setPreferredSize(new Dimension(width, height));
        internship.setSize(width, height);
    }
    
    static void showLogin() {
        setsize(400, 255);
        cl.show(pane, LOGIN);
    }
    
    static void showStudentReg() {
        setsize(599, 300);
        cl.show(pane, STUDENTREG);
    }
    
    static void setListeners() {
        login.loginB.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                showStudentReg();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(Exception ex) {
            System.err.println("err main 01:"+ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    internship = new Internship();
                    login = new Login();
                    studentReg = new StudentReg();
                    
                    Class.forName("com.mysql.jdbc.Driver");
                    conn = DriverManager.getConnection("jdbc:mysql://10.5.18.66:3306/12CS30001", "12CS30001", "dual12");
                    st = conn.createStatement();
                    rs = st.executeQuery("SELECT * FROM dept_degree LIMIT 10");
                    while(rs.next()) {
                        System.out.println(rs.getInt("dept_degree_id") + '\t' + rs.getString("department"));
                    }
                    
                    internship.setResizable(false);
                    internship.pack();
                    internship.setVisible(true);
                    
                    pane = internship.getContentPane();
                    pane.setLayout(new CardLayout());
                    cl = (CardLayout)pane.getLayout();
                    
                    pane.add(login, LOGIN);
                    pane.add(studentReg, STUDENTREG);
                    
                    setListeners();
                    showLogin();
                } catch (Exception ex) {
                    System.err.println("err main 02:"+ex);
                }
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
